version: '2.1'
services:
  api-gateway:
    build: .
    environment:
      PORT: '3000'
      SHOW_URLS: 'true'


      MULTIMEDIA_URL: '34.69.30.153'
      MULTIMEDIA_PORT: '9000'
      MULTIMEDIA_BASE_ENDPOINT: 'api/multimedia'
      
      SEARCH_URL: '3.92.233.187'
      SEARCH_PORT: '1859'
      SEARCH_BASE_ENDPOINT: ''

      UBICATION_URL: '35.223.99.92'
      UBICATION_PORT: '5500'
      UBICATION_BASE_ENDPOINT: 'sa-auth-ms/resources/users'      

      COMMENTS_URL: '35.202.88.71'
      COMMENTS_PORT: '5000'

      LOSPRECIOS_URL: 'losprecios.co'
      LOSPRECIOS_API: 'uExmJrA_831WXmWr'
       
      USER_URL: '35.223.99.92'
      USER_PORT: '5000'
      USER_BASE_ENDPOINT: 'perime-user-ms/user'
      SESSION_MOVIL_BASE_ENDPOINT: 'perime-user-ms/sessionm'
      SESSION_WEB_BASE_ENDPOINT: 'perime-user-ms/sessionw'
      VALIDATE_BASE_ENDPOINT: 'perime-user-ms/validate'
      
      PUBLICATION_URL: '35.202.88.71'
      PUBLICATION_PORT: '3000'
      PUBLICATION_BASE_ENDPOINT: 'publications'
            
      
    ports:
      - '3000:3000'
