version: '2.1'
services:
  api-gateway:
    build: .
    environment:
      PORT: '3000'
      SHOW_URLS: 'true'

      MULTIMEDIA_URL: 'ec2-54-173-77-159.compute-1.amazonaws.com'
      MULTIMEDIA_PORT: '9000'
      MULTIMEDIA_BASE_ENDPOINT: 'api/multimedia'

      SEARCH_URL: '54.243.11.62'
      SEARCH_PORT: '1859'
      SEARCH_BASE_ENDPOINT: ''

      UBICATION_URL: 'ec2-3-81-233-113.compute-1.amazonaws.com'
      UBICATION_PORT: '5500'
      UBICATION_BASE_ENDPOINT: 'sa-auth-ms/resources/users'      

      COMMENTS_URL: '34.71.22.6'
      COMMENTS_PORT: '5000'

      LOSPRECIOS_URL: '54.243.11.62'
      
    ports:
      - '3000:3000'
