export const context = {
    /* MULTIMEDIA MICROSERVICE CONNECTIONS VARS */
    MULTIMEDIA_URL: process.env.MULTIMEDIA_URL,
    MULTIMEDIA_PORT: process.env.MULTIMEDIA_PORT,
    MULTIMEDIA_BASE_ENDPOINT: process.env.MULTIMEDIA_BASE_ENDPOINT,

    /* UBICATION MICROSERVICE CONNECTIONS VARS */
    AUTH_URL: process.env.AUTH_URL,
    AUTH_PORT: process.env.AUTH_PORT,
    AUTH_USERS_ENTRY: process.env.AUTH_USERS_ENTRY
    
    
    /* ADD ANOTHERS ENVIROMENTS VARS ... */
}