export const context = {

    /* MULTIMEDIA MICROSERVICE CONNECTIONS VARS */

    MULTIMEDIA_URL: process.env.MULTIMEDIA_URL || "ec2-54-173-77-159.compute-1.amazonaws.com",
    MULTIMEDIA_PORT: process.env.MULTIMEDIA_PORT || "9000",
    MULTIMEDIA_BASE_ENDPOINT: process.env.MULTIMEDIA_BASE_ENDPOINT || "api/multimedia",

    /* SEARCH MICROSERVICE CONNECTIONS VARS ... */
    SEARCH_URL: process.env.SEARCH_URL,
    SEARCH_PORT: process.env.SEARCH_PORT,
    SEARCH_BASE_ENDPOINT: process.env.SEARCH_BASE_ENDPOINT,

    /* UBICATION MICROSERVICE CONNECTIONS VARS */
    UBICATION_URL: process.env.UBICATION_URL,
    UBICATION_PORT: process.env.UBICATION_PORT,
    UBICATION_BASE_ENDPOINT: process.env.UBICATION_BASE_ENDPOINT,
    
    /* COMMENTS MICROSERVICE CONNECTIONS VARS */
    COMMENTS_URL: process.env.COMMENTS_URL,
    COMMENTS_PORT: process.env.COMMENTS_PORT,

    /* LOSPRECIOS EXTERNAL CONNECTIONS VARS */
    LOSPRECIOS_URL: process.env.LOSPRECIOS_URL,
    LOSPRECIOS_API: process.env.LOSPRECIOS_API,

    /* USER MICROSERVICE CONNECTIONS VARS */
    USER_URL: process.env.USER_URL || "localhost",
    USER_PORT: process.env.USER_PORT || "5000",
    USER_BASE_ENDPOINT: process.env.USER_BASE_ENDPOINT || 'perime-user-ms/user',
    SESSION_MOVIL_BASE_ENDPOINT: process.env.SESSION_MOVIL_BASE_ENDPOINT || 'perime-user-ms/sessionm',
    SESSION_WEB_BASE_ENDPOINT: process.env.SESSION_WEB_BASE_ENDPOINT || 'perime-user-ms/sessionw',
    VALIDATE_BASE_ENDPOINT: process.env.VALIDATE_BASE_ENDPOINT || 'perime-user-ms/validate',

    /* PUBLICATION MICROSERVICE CONNECTIONS VARS */
    PUBLICATION_URL: process.env.PUBLICATION_URL,
    PUBLICATION_PORT: process.env.PUBLICATION_PORT,
    PUBLICATION_BASE_ENDPOINT: process.env.PUBLICATION_BASE_ENDPOINT  
}


