export const context = {
    /* MULTIMEDIA MICROSERVICE CONNECTIONS VARS */
    MULTIMEDIA_URL: process.env.MULTIMEDIA_URL,
    MULTIMEDIA_PORT: process.env.MULTIMEDIA_PORT,
    MULTIMEDIA_BASE_ENDPOINT: process.env.MULTIMEDIA_BASE_ENDPOINT,

    /* BUSQUEDA MICROSERVICE CONNECTIONS VARS ... */
    BUSQUEDA_URL: process.env.BUSQUEDA_URL,
    BUSQUEDA_PORT: process.env.BUSQUEDA_PORT,
    BUSQUEDA_BASE_ENDPOINT: process.env.BUSQUEDA_BASE_ENDPOINT
}